import { Inter, JetBrains_Mono } from 'next/font/google';
import Script from 'next/script';

import { Layout } from '@/commons/layout';
import { AuthProvider } from '@/commons/providers/auth/auth.provider';

import type { Metadata } from 'next';

import './globals.css';

const geistSans = Inter({
  subsets: ['latin'],
  variable: '--font-geist-sans',
});
const geistMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        {/* no-sync-scripts 규칙 에러가 떠서 동기 script를 Script 컴포넌트로 변경함 */}
        <Script
          id="tmap-sdk"
          strategy="afterInteractive"
          src={`https://apis.openapi.sk.com/tmap/jsv2?version=1&appKey=${process.env.NEXT_PUBLIC_TMAP_API_KEY}`}
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <Layout>{children}</Layout>
        </AuthProvider>
      </body>
    </html>
  );
}
